name: Build, flatten, push

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Flatten dist to release branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # stupid but easy method
          cp package.json package-lock.json /tmp/
          git checkout --orphan release
          git rm -rf .
          rm -rf .github
          rm -rf node_modules
          rm -f tsconfig.json
          rm -f .gitignore
          cp -r dist/* ./
          rm -rf dist
          cp /tmp/package.json /tmp/package-lock.json ./
          git add .
          git commit -m "Release build"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:release